#!/usr/bin/env python3
"""
Analyze batch test log files and count the number of test cases generated by LLM and the number of successfully executed test cases（PyTorch → TensorFlow）
"""
import re

def analyze_log_file(log_file_path):
    total_llm_cases = 0
    total_successful_cases = 0
    operator_count = 0
    operator_details = []
    
    with open(log_file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    pattern = r'\[(\d+)/(\d+)\]\s+(\S+)\s+state:\s+✅\s+Finish\s+Total number of iterations:\s+(\d+)\s+LLMNumber of use cases generated:\s+(\d+)\s+Number of successfully executed use cases:\s+(\d+)(?:\s+success rate:\s+([\d.]+)%)?'
    matches = re.findall(pattern, content)
    
    for match in matches:
        seq_num, total_ops, operator_name, iterations, llm_cases, successful_cases, *success_rate = match
        llm_cases = int(llm_cases)
        successful_cases = int(successful_cases)
        total_llm_cases += llm_cases
        total_successful_cases += successful_cases
        operator_count += 1
        rate = (successful_cases / llm_cases) * 100 if llm_cases > 0 else 0.0
        operator_details.append({
            'seq': int(seq_num),
            'name': operator_name,
            'llm_cases': llm_cases,
            'successful_cases': successful_cases,
            'success_rate': rate
        })
    
    return {
        'operator_count': operator_count,
        'total_llm_cases': total_llm_cases,
        'total_successful_cases': total_successful_cases,
        'overall_success_rate': (total_successful_cases / total_llm_cases * 100) if total_llm_cases > 0 else 0,
        'operator_details': operator_details
    }

def print_statistics(stats):
    print("="*80)
    print("📊 Batch test log statistical analysis（PyTorch → TensorFlow）")
    print("="*80)
    print(f"\n✅ Total number of test operators: {stats['operator_count']}")
    print(f"📝 LLMTotal number of use cases generated: {stats['total_llm_cases']}")
    print(f"✅ Total number of successfully executed use cases: {stats['total_successful_cases']}")
    print(f"📈 overall success rate: {stats['overall_success_rate']:.2f}%")
    
    success_rate_distribution = {
        '0%': 0,
        '1-25%': 0,
        '26-50%': 0,
        '51-75%': 0,
        '76-99%': 0,
        '100%': 0
    }
    for op in stats['operator_details']:
        rate = op['success_rate']
        if rate == 0:
            success_rate_distribution['0%'] += 1
        elif rate <= 25:
            success_rate_distribution['1-25%'] += 1
        elif rate <= 50:
            success_rate_distribution['26-50%'] += 1
        elif rate <= 75:
            success_rate_distribution['51-75%'] += 1
        elif rate < 100:
            success_rate_distribution['76-99%'] += 1
        else:
            success_rate_distribution['100%'] += 1
    print(f"\n📊 Success rate distribution:")
    for range_name, count in success_rate_distribution.items():
        percentage = (count / stats['operator_count'] * 100) if stats['operator_count'] > 0 else 0
        print(f"  {range_name:10s}: {count:3d} an operator ({percentage:5.2f}%)")
    
    print(f"\n🏆 The top 10 operators with the highest success rate:")
    sorted_ops = sorted(stats['operator_details'], key=lambda x: x['success_rate'], reverse=True)
    for i, op in enumerate(sorted_ops[:10], 1):
        print(f"  {i:2d}. {op['name']:40s} - {op['successful_cases']}/{op['llm_cases']} ({op['success_rate']:.2f}%)")
    
    zero_success_ops = [op for op in stats['operator_details'] if op['success_rate'] == 0 and op['llm_cases'] > 0]
    if zero_success_ops:
        print(f"\n⚠️ Operators with a success rate of 0 (total{len(zero_success_ops)}indivual）:")
        for op in zero_success_ops[:20]:
            print(f"  - {op['name']:40s} (LLMGenerated{op['llm_cases']}use cases)")
        if len(zero_success_ops) > 20:
            print(f"  ... besides {len(zero_success_ops) - 20} an operator")

def merge_statistics(all_stats_list):
    merged_stats = {
        'operator_count': 0,
        'total_llm_cases': 0,
        'total_successful_cases': 0,
        'overall_success_rate': 0,
        'operator_details': []
    }
    operator_dict = {}
    for stats in all_stats_list:
        merged_stats['operator_count'] += stats['operator_count']
        merged_stats['total_llm_cases'] += stats['total_llm_cases']
        merged_stats['total_successful_cases'] += stats['total_successful_cases']
        for op in stats['operator_details']:
            op_name = op['name']
            if op_name in operator_dict:
                operator_dict[op_name]['llm_cases'] += op['llm_cases']
                operator_dict[op_name]['successful_cases'] += op['successful_cases']
                lc = operator_dict[op_name]['llm_cases']
                operator_dict[op_name]['success_rate'] = (operator_dict[op_name]['successful_cases'] / lc * 100) if lc > 0 else 0.0
            else:
                operator_dict[op_name] = {
                    'seq': op['seq'],
                    'name': op_name,
                    'llm_cases': op['llm_cases'],
                    'successful_cases': op['successful_cases'],
                    'success_rate': op['success_rate']
                }
    merged_stats['operator_details'] = list(operator_dict.values())
    if merged_stats['total_llm_cases'] > 0:
        merged_stats['overall_success_rate'] = merged_stats['total_successful_cases'] / merged_stats['total_llm_cases'] * 100
    merged_stats['operator_count'] = len(merged_stats['operator_details'])
    return merged_stats

if __name__ == "__main__":
    log_files = [
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251215_162151.txt",
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251215_163032.txt",
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251215_171217.txt",
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251215_200801.txt",
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251215_225440.txt",
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251215_234447.txt",
        r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log\batch_test_log_20251216_002607.txt",

        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_130821.txt",
        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_151945.txt",
        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_165129.txt",
        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_170300.txt",
        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_182808.txt",
        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_183252.txt",
        # r"d:\graduate\DFrameworkTest\pt_tf_test\pt_tf_log_1\batch_test_log_20260123_201401.txt",
    ]
    
    print("="*80)
    print("📊 Statistical analysis of batch log files（PyTorch → TensorFlow）")
    print("="*80)
    print(f"\n📂 Total analysis {len(log_files)} log files:\n")
    
    all_stats_list = []
    for i, log_file in enumerate(log_files, 1):
        print(f"  {i}. {log_file.split('/')[-1]}")
        try:
            stats = analyze_log_file(log_file)
            all_stats_list.append(stats)
            print(f"     ✅ success - {stats['operator_count']}an operator, {stats['total_llm_cases']}LLM use cases, {stats['total_successful_cases']}a success")
        except FileNotFoundError:
            print(f"     ❌ File does not exist, skip")
        except Exception as e:
            print(f"     ❌ Analysis failed: {e}")
    
    if not all_stats_list:
        print("\n❌ No log files were successfully analyzed")
        raise SystemExit(1)
    
    print(f"\n{'='*80}")
    print("📊 Combine statistical results")
    print("="*80)
    merged_stats = merge_statistics(all_stats_list)
    print_statistics(merged_stats)
    print("\n" + "="*80)
    print("✅ Analysis completed")
    print("="*80)
