# ./pt_tf_test/compare_llm_vs_rulebased.py
"""
LLMMethod vs rule method：PyTorch -> TensorFlow Test case conversion success rate comparison
================================================================

Compare two cross-framework test case migration solutions：
1. LLMMethod: Execute the initial use case -> Call LLM to repair/Mutation (fixed 1 iteration） -> Execute new TF use cases generated by LLM
2. Rule method: only automatically convert operator name and data type（dtype） -> New TF use cases generated by execution rules  Core comparison indicator: whether the "new TF use case generated" by the two methods can be executed normally (tensorflow_success).  Output: - Real-time results: JSONL (one row per case) - Summary results: JSON (global statistics + Operator level details）
"""

import argparse
import copy
import json
import os
import sys
import tempfile
import time
import traceback
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from threading import Lock, RLock
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import tensorflow as tf
import torch

# Add project root directory to path
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from pt_tf_test.llm_enhanced_compare import (
    DEFAULT_KEY_PATH,
    DEFAULT_MODEL,
    LLMEnhancedComparator,
)

DEFAULT_MAX_ITERATIONS = 1
DEFAULT_NUM_CASES = 3
DEFAULT_WORKERS = 4


def safe_print(msg: str, print_lock: Optional[Lock] = None, end: str = "\n") -> None:
    """Thread safe printing"""
    if print_lock:
        with print_lock:
            print(msg, end=end, flush=True)
    else:
        print(msg, end=end, flush=True)


class RuleBasedConverter:
    """
    Rule converter: only performs API name and dtype related conversions.      Design constraints:     - LLM is not used.     - Don't try complex semantic fixes, just automate names/type conversion。
    """

    def __init__(self) -> None:
        self.tf_dtype_map = {
            "torch.float16": tf.float16,
            "torch.float32": tf.float32,
            "torch.float64": tf.float64,
            "torch.bfloat16": tf.bfloat16,
            "torch.int8": tf.int8,
            "torch.uint8": tf.uint8,
            "torch.int16": tf.int16,
            "torch.int32": tf.int32,
            "torch.int64": tf.int64,
            "torch.bool": tf.bool,
            "float16": tf.float16,
            "float32": tf.float32,
            "float64": tf.float64,
            "bfloat16": tf.bfloat16,
            "int8": tf.int8,
            "uint8": tf.uint8,
            "int16": tf.int16,
            "int32": tf.int32,
            "int64": tf.int64,
            "bool": tf.bool,
        }

    @staticmethod
    def _is_tensor_desc(value: Any) -> bool:
        return isinstance(value, dict) and "shape" in value and "dtype" in value

    @staticmethod
    def _normalize_tensor_desc_dtype(dtype_value: Any) -> Any:
        """
        The dtype in the tensor description is kept as a string to facilitate subsequent numpy data generation logic compatibility.         For example torch.float32 -> float32。
        """
        if not isinstance(dtype_value, str):
            return dtype_value
        if dtype_value.startswith("torch."):
            return dtype_value.split(".", 1)[1]
        return dtype_value

    def _convert_dtype_param_value(self, value: Any) -> Any:
        """Convert the dtype argument to a TensorFlow-recognizable dtype object。"""
        if isinstance(value, tf.dtypes.DType):
            return value
        if isinstance(value, str):
            normalized = value.strip()
            if normalized.startswith("tf."):
                normalized = normalized.split(".", 1)[1]
            if normalized.startswith("torch."):
                return self.tf_dtype_map.get(normalized, tf.float32)
            return self.tf_dtype_map.get(normalized, tf.float32)
        if isinstance(value, int):
            # Common integer encoding tips
            int_map = {
                0: tf.float32,
                1: tf.float64,
                2: tf.int32,
                3: tf.uint8,
                4: tf.int16,
                5: tf.int8,
                6: tf.int64,
                7: tf.bool,
            }
            return int_map.get(value, tf.float32)
        return value

    def _convert_recursive(self, value: Any) -> Any:
        if isinstance(value, dict):
            if self._is_tensor_desc(value):
                converted = dict(value)
                converted["dtype"] = self._normalize_tensor_desc_dtype(converted.get("dtype"))
                return converted

            converted_dict: Dict[str, Any] = {}
            for key, child in value.items():
                if key == "dtype":
                    converted_dict[key] = self._convert_dtype_param_value(child)
                else:
                    converted_dict[key] = self._convert_recursive(child)
            return converted_dict

        if isinstance(value, list):
            return [self._convert_recursive(item) for item in value]

        if isinstance(value, tuple):
            return tuple(self._convert_recursive(item) for item in value)

        if isinstance(value, str):
            # Only perform lightweight string dtype normalization to avoid affecting non-dtype parameter semantics。
            if value.startswith("torch.") and value in self.tf_dtype_map:
                mapped = self.tf_dtype_map[value]
                return mapped
            return value

        return value

    def convert_torch_case_to_tf_case(self, torch_test_case: Dict[str, Any], tf_api: str) -> Dict[str, Any]:
        """Convert PyTorch test cases to TensorFlow test cases based on rules。"""
        converted = self._convert_recursive(copy.deepcopy(torch_test_case))
        converted["api"] = tf_api
        return converted


class LLMvsRuleBasedComparator:
    """Comparison of unified management LLM approach and rules approach。"""

    def __init__(
        self,
        key_path: str = DEFAULT_KEY_PATH,
        model: str = DEFAULT_MODEL,
        num_workers: int = DEFAULT_WORKERS,
    ) -> None:
        self.print_lock = Lock()
        self.realtime_lock = Lock()
        self.execution_lock = RLock()

        self.num_workers = max(1, int(num_workers))

        self.llm_method = LLMEnhancedComparator(
            key_path=key_path,
            model=model,
            print_lock=self.print_lock,
            llm_workers=self.num_workers,
        )
        self.rule_converter = RuleBasedConverter()

        self.result_dir = os.path.join(ROOT_DIR, "pt_tf_test")
        os.makedirs(self.result_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.realtime_file_path = os.path.join(
            self.result_dir, f"llm_vs_rulebased_realtime_{timestamp}.jsonl"
        )
        self.realtime_file = open(self.realtime_file_path, "a", encoding="utf-8")

    def _safe_print(self, msg: str, end: str = "\n") -> None:
        safe_print(msg, self.print_lock, end)

    def _append_realtime_record(self, record: Dict[str, Any]) -> None:
        with self.realtime_lock:
            self.realtime_file.write(json.dumps(self._make_serializable(record), ensure_ascii=False) + "\n")
            self.realtime_file.flush()

    def run_comparison(
        self,
        operator_names: List[str],
        num_cases: int = DEFAULT_NUM_CASES,
        max_iterations: int = DEFAULT_MAX_ITERATIONS,
    ) -> Dict[str, Any]:
        """
        Run a comparison experiment.          Note: The number of LLM iterations in this ablation experiment is fixed at 1。
        """
        if max_iterations != 1:
            self._safe_print("⚠️ Current ablation experiment is fixedmax_iterations=1，Enforced1")
        max_iterations = 1

        global_stats = {
            "total_operators": len(operator_names),
            "tested_operators": 0,
            "skipped_operators_no_tf": 0,
            "skipped_operators_all_llm_skip": 0,
            "skipped_operators_deprecated": 0,
            "llm_generated_total": 0,
            "llm_tf_success": 0,
            "rule_generated_total": 0,
            "rule_tf_success": 0,
        }

        operator_details: List[Dict[str, Any]] = []

        for index, operator_name in enumerate(operator_names, 1):
            self._safe_print("\n" + "=" * 72)
            self._safe_print(f"[{index}/{len(operator_names)}] operator: {operator_name}")
            self._safe_print("=" * 72)

            torch_api, tf_api, mapping_method = self.llm_method.convert_api_name(operator_name)
            if tf_api is None:
                self._safe_print(f"  ⏭️ No TF mapping（{mapping_method}），jump over")
                global_stats["skipped_operators_no_tf"] += 1
                operator_details.append(
                    {
                        "operator": operator_name,
                        "status": "skipped_no_tf",
                        "mapping_method": mapping_method,
                    }
                )
                continue

            self._safe_print(f"  PT: {torch_api} -> TF: {tf_api}")

            document = self.llm_method.collection.find_one({"api": operator_name})
            if document is None:
                self._safe_print("  ❌ The operator is not found in the database and is skipped.")
                operator_details.append({"operator": operator_name, "status": "not_found"})
                continue

            total_cases = self.llm_method.get_num_test_cases_from_document(document)
            actual_cases = min(max(1, num_cases), total_cases)

            self._safe_print("  📖 Prefetch API documentation (for use by LLM）...")
            torch_doc, tf_doc = self.llm_method._fetch_api_docs(torch_api, tf_api)

            operator_result = self._test_single_operator(
                operator_name=operator_name,
                torch_api=torch_api,
                tf_api=tf_api,
                document=document,
                num_cases=actual_cases,
                torch_doc=torch_doc,
                tf_doc=tf_doc,
            )
            operator_details.append(operator_result)

            if operator_result["status"] == "skipped_deprecated":
                global_stats["skipped_operators_deprecated"] += 1
                continue
            if operator_result["status"] == "skipped_all_llm_skip":
                global_stats["skipped_operators_all_llm_skip"] += 1
                continue

            global_stats["tested_operators"] += 1
            global_stats["llm_generated_total"] += operator_result["llm_generated_total"]
            global_stats["llm_tf_success"] += operator_result["llm_tf_success"]
            global_stats["rule_generated_total"] += operator_result["rule_generated_total"]
            global_stats["rule_tf_success"] += operator_result["rule_tf_success"]

        return {"global_stats": global_stats, "operator_details": operator_details}

    def _test_single_operator(
        self,
        operator_name: str,
        torch_api: str,
        tf_api: str,
        document: Dict[str, Any],
        num_cases: int,
        torch_doc: str,
        tf_doc: str,
    ) -> Dict[str, Any]:
        op_result: Dict[str, Any] = {
            "operator": operator_name,
            "torch_api": torch_api,
            "tf_api": tf_api,
            "num_cases": num_cases,
            "status": "completed",
            "llm_generated_total": 0,
            "llm_tf_success": 0,
            "rule_generated_total": 0,
            "rule_tf_success": 0,
            "case_details": [],
        }

        initial_cases: List[Tuple[int, Dict[str, Any]]] = []
        for case_idx in range(num_cases):
            tc = self.llm_method.prepare_shared_numpy_data(document, case_index=case_idx)
            tc["api"] = torch_api
            initial_cases.append((case_idx + 1, tc))

        if self.num_workers <= 1:
            case_results = [
                self._process_single_case(torch_api, tf_api, case_number, tc, torch_doc, tf_doc)
                for case_number, tc in initial_cases
            ]
        else:
            case_results = []
            with ThreadPoolExecutor(max_workers=self.num_workers) as executor:
                futures = {
                    executor.submit(
                        self._process_single_case,
                        torch_api,
                        tf_api,
                        case_number,
                        tc,
                        torch_doc,
                        tf_doc,
                    ): case_number
                    for case_number, tc in initial_cases
                }
                for future in as_completed(futures):
                    case_results.append(future.result())

        case_results.sort(key=lambda item: item["case_number"])

        # If an elimination operator is detected in any case, the operator will be skipped as a whole.
        if any(item.get("deprecated_skip", False) for item in case_results):
            op_result["status"] = "skipped_deprecated"
            op_result["case_details"] = case_results
            self._safe_print("  ⏭️ It is detected that the operator version is obsolete and the operator is skipped.")
            return op_result

        # If all cases are skipped by LLM, the operator will be eliminated from the comparison.
        if case_results and all(item.get("llm_skipped", False) for item in case_results):
            op_result["status"] = "skipped_all_llm_skip"
            op_result["case_details"] = case_results
            self._safe_print("  ⏭️ All use cases of this operator are skipped by LLM and eliminated.")
            return op_result

        for item in case_results:
            if item.get("llm_skipped", False):
                # Keep the same caliber as the reference script: LLM skip cases are not included in the denominator on both sides.
                continue
            op_result["llm_generated_total"] += item.get("llm_generated_total", 0)
            op_result["llm_tf_success"] += item.get("llm_tf_success", 0)
            op_result["rule_generated_total"] += item.get("rule_generated_total", 0)
            op_result["rule_tf_success"] += item.get("rule_tf_success", 0)

        op_result["case_details"] = case_results
        return op_result

    def _process_single_case(
        self,
        torch_api: str,
        tf_api: str,
        case_number: int,
        initial_torch_case: Dict[str, Any],
        torch_doc: str,
        tf_doc: str,
    ) -> Dict[str, Any]:
        """Processing a single use case in parallel: the rules approach + LLMmethod。"""
        case_result: Dict[str, Any] = {
            "case_number": case_number,
            "llm_skipped": False,
            "deprecated_skip": False,
            "llm_generated_total": 0,
            "llm_tf_success": 0,
            "rule_generated_total": 1,
            "rule_tf_success": 0,
            "rule_detail": {},
            "llm_detail": {},
        }

        # ------------------------------
        # 1) Rule method: do name only/dtypeConvert
        # ------------------------------
        rule_tf_case = self.rule_converter.convert_torch_case_to_tf_case(initial_torch_case, tf_api)

        self._safe_print(f"  [use case{case_number}] Rule method execution...", end="")
        try:
            with self.execution_lock:
                rule_exec = self.llm_method._execute_test_case_sequential(
                    torch_api,
                    tf_api,
                    initial_torch_case,
                    rule_tf_case,
                )
            rule_tf_ok = bool(rule_exec.get("tensorflow_success", False))
            case_result["rule_tf_success"] = 1 if rule_tf_ok else 0
            self._safe_print(f" TF:{'✓' if rule_tf_ok else '✗'}")
        except Exception as error:
            rule_exec = {
                "status": "fatal_error",
                "tensorflow_success": False,
                "error": str(error),
                "traceback": traceback.format_exc(),
            }
            self._safe_print(f" TF:✗ ({str(error)[:80]})")

        case_result["rule_detail"] = {
            "generated_tf_test_case": rule_tf_case,
            "execution_result": rule_exec,
        }

        # ------------------------------
        # 2) LLMMethod: Fixed 1 iteration
        # ------------------------------
        initial_tf_case = copy.deepcopy(initial_torch_case)
        initial_tf_case["api"] = tf_api

        self._safe_print(f"  [use case{case_number}] LLMinitial execution...", end="")
        try:
            with self.execution_lock:
                initial_exec = self.llm_method._execute_test_case_sequential(
                    torch_api,
                    tf_api,
                    initial_torch_case,
                    initial_tf_case,
                )
            self._safe_print(
                f" PT:{'✓' if initial_exec.get('torch_success') else '✗'}"
                f" TF:{'✓' if initial_exec.get('tensorflow_success') else '✗'}"
            )
        except Exception as error:
            initial_exec = {
                "torch_api": torch_api,
                "tensorflow_api": tf_api,
                "status": "fatal_error",
                "torch_success": False,
                "tensorflow_success": False,
                "results_match": False,
                "torch_error": str(error),
                "tensorflow_error": None,
                "comparison_error": None,
            }
            self._safe_print(f" PT:✗ TF:✗ ({str(error)[:80]})")

        torch_error = str(initial_exec.get("torch_error", ""))
        if (not initial_exec.get("torch_success", False)) and torch_error:
            if any(keyword in torch_error.lower() for keyword in ["deprecated", "removed"]):
                case_result["deprecated_skip"] = True
                case_result["llm_detail"] = {
                    "initial_exec": initial_exec,
                    "llm_operation": "skip",
                    "llm_reason": "PyTorchThe operator has been eliminated by the version",
                }
                self._append_realtime_record(
                    {
                        "timestamp": datetime.now().isoformat(),
                        "operator": torch_api,
                        "case_number": case_number,
                        "status": "skipped_deprecated",
                        "llm_skipped": False,
                        "deprecated_skip": True,
                        "llm_tf_success": False,
                        "rule_tf_success": bool(case_result["rule_tf_success"]),
                    }
                )
                return case_result

        self._safe_print(f"  [use case{case_number}] callLLM...", end="")
        llm_result = self.llm_method.call_llm_for_repair_or_mutation(
            initial_exec,
            initial_torch_case,
            initial_tf_case,
            torch_doc,
            tf_doc,
        )
        operation = llm_result.get("operation", "skip")
        reason = str(llm_result.get("reason", ""))
        self._safe_print(f" {operation} - {reason[:70]}")

        if operation == "skip":
            case_result["llm_skipped"] = True
            case_result["llm_detail"] = {
                "initial_exec": initial_exec,
                "llm_operation": operation,
                "llm_reason": reason,
            }
            self._append_realtime_record(
                {
                    "timestamp": datetime.now().isoformat(),
                    "operator": torch_api,
                    "case_number": case_number,
                    "status": "llm_skip",
                    "llm_skipped": True,
                    "deprecated_skip": False,
                    "llm_tf_success": False,
                    "rule_tf_success": bool(case_result["rule_tf_success"]),
                }
            )
            return case_result

        llm_pt_case = llm_result.get("pytorch_test_case", initial_torch_case)
        llm_tf_case = llm_result.get("tensorflow_test_case", initial_tf_case)

        try:
            llm_pt_case, llm_tf_case = self.llm_method._convert_llm_test_cases(llm_pt_case, llm_tf_case)
        except Exception as error:
            case_result["llm_skipped"] = True
            case_result["llm_detail"] = {
                "initial_exec": initial_exec,
                "llm_operation": "skip",
                "llm_reason": f"LLMUse case conversion failed: {error}",
            }
            self._safe_print(f"  [use case{case_number}] LLMUse case conversion failed, skipped: {str(error)[:70]}")
            self._append_realtime_record(
                {
                    "timestamp": datetime.now().isoformat(),
                    "operator": torch_api,
                    "case_number": case_number,
                    "status": "llm_case_convert_failed",
                    "llm_skipped": True,
                    "deprecated_skip": False,
                    "llm_tf_success": False,
                    "rule_tf_success": bool(case_result["rule_tf_success"]),
                }
            )
            return case_result

        case_result["llm_generated_total"] = 1

        self._safe_print(f"  [use case{case_number}] Execute LLM to generate use cases...", end="")
        try:
            with self.execution_lock:
                llm_exec = self.llm_method._execute_test_case_sequential(
                    torch_api,
                    tf_api,
                    llm_pt_case,
                    llm_tf_case,
                )
            llm_tf_ok = bool(llm_exec.get("tensorflow_success", False))
            case_result["llm_tf_success"] = 1 if llm_tf_ok else 0
            self._safe_print(
                f" PT:{'✓' if llm_exec.get('torch_success') else '✗'}"
                f" TF:{'✓' if llm_tf_ok else '✗'}"
            )
        except Exception as error:
            llm_exec = {
                "status": "fatal_error",
                "torch_success": False,
                "tensorflow_success": False,
                "results_match": False,
                "error": str(error),
                "traceback": traceback.format_exc(),
            }
            self._safe_print(f" PT:✗ TF:✗ ({str(error)[:80]})")

        case_result["llm_detail"] = {
            "initial_exec": initial_exec,
            "llm_operation": operation,
            "llm_reason": reason,
            "generated_pt_test_case": llm_pt_case,
            "generated_tf_test_case": llm_tf_case,
            "generated_exec": llm_exec,
        }

        self._append_realtime_record(
            {
                "timestamp": datetime.now().isoformat(),
                "operator": torch_api,
                "case_number": case_number,
                "status": "completed",
                "llm_skipped": False,
                "deprecated_skip": False,
                "llm_tf_success": bool(case_result["llm_tf_success"]),
                "rule_tf_success": bool(case_result["rule_tf_success"]),
                "llm_operation": operation,
            }
        )

        return case_result

    def print_and_save_results(self, result: Dict[str, Any]) -> str:
        """Print and save final summary results。"""
        stats = result["global_stats"]

        print("\n" + "=" * 80)
        print("📊 LLMMethod vs Rule Method (name only+dtypeautomatic conversion）")
        print("=" * 80)
        print(f"Total number of operators: {stats['total_operators']}")
        print(f"- Skip without TF mapping: {stats['skipped_operators_no_tf']}")
        print(f"- LLMAll skip operator: {stats['skipped_operators_all_llm_skip']}")
        print(f"- Version elimination skip operator: {stats['skipped_operators_deprecated']}")
        print(f"- Actual participation comparison: {stats['tested_operators']}")

        llm_total = stats["llm_generated_total"]
        llm_success = stats["llm_tf_success"]
        llm_rate = (llm_success / llm_total * 100.0) if llm_total > 0 else 0.0

        rule_total = stats["rule_generated_total"]
        rule_success = stats["rule_tf_success"]
        rule_rate = (rule_success / rule_total * 100.0) if rule_total > 0 else 0.0

        print("\n" + "-" * 48)
        print("🤖 LLMmethod (new TF use case generated）")
        print(f"- Number of use cases generated: {llm_total}")
        print(f"- TFNumber of successful executions: {llm_success}")
        print(f"- TFExecution success rate: {llm_rate:.2f}%" if llm_total > 0 else "- TFExecution success rate: N/A")

        print("\n" + "-" * 48)
        print("🧪 Rule method (new TF use case generated）")
        print(f"- Number of use cases generated: {rule_total}")
        print(f"- TFNumber of successful executions: {rule_success}")
        print(f"- TFExecution success rate: {rule_rate:.2f}%" if rule_total > 0 else "- TFExecution success rate: N/A")

        print("\n" + "-" * 48)
        if llm_total > 0 and rule_total > 0:
            diff = llm_rate - rule_rate
            if diff > 0:
                print(f"in conclusion: LLMMethod is higher than rule method {diff:.2f} percentage points")
            elif diff < 0:
                print(f"in conclusion: The rule method is superior to the LLM method {-diff:.2f} percentage points")
            else:
                print("in conclusion: Both methods are equal")
        else:
            print("in conclusion: Insufficient statistical samples for comparison")

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        result_file = os.path.join(self.result_dir, f"llm_vs_rulebased_result_{timestamp}.json")

        result_to_save = self._make_serializable(result)
        result_to_save["summary"] = {
            "llm_tf_success_rate": f"{llm_rate:.2f}%" if llm_total > 0 else "N/A",
            "rule_tf_success_rate": f"{rule_rate:.2f}%" if rule_total > 0 else "N/A",
            "timestamp": datetime.now().isoformat(),
        }

        self._atomic_dump_json(result_file, result_to_save)

        print("=" * 80)
        print(f"💾 real timeJSONL: {self.realtime_file_path}")
        print(f"💾 SummaryJSON: {result_file}")

        return result_file

    @staticmethod
    def _atomic_dump_json(file_path: str, data: Dict[str, Any]) -> None:
        """Atomic writing to avoid JSON truncation caused by interruption in the middle。"""
        file_dir = os.path.dirname(file_path)
        os.makedirs(file_dir, exist_ok=True)

        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            suffix=".tmp",
            prefix="tmp_result_",
            dir=file_dir,
            delete=False,
        ) as temp_file:
            temp_path = temp_file.name
            json.dump(data, temp_file, indent=2, ensure_ascii=False)
            temp_file.flush()
            os.fsync(temp_file.fileno())

        os.replace(temp_path, file_path)

    @staticmethod
    def _make_serializable(obj: Any) -> Any:
        if isinstance(obj, dict):
            return {k: LLMvsRuleBasedComparator._make_serializable(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [LLMvsRuleBasedComparator._make_serializable(item) for item in obj]
        if isinstance(obj, tuple):
            return [LLMvsRuleBasedComparator._make_serializable(item) for item in obj]
        if isinstance(obj, np.ndarray):
            return {
                "__type__": "ndarray",
                "shape": list(obj.shape),
                "dtype": str(obj.dtype),
            }
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, torch.Tensor):
            return {
                "__type__": "tensor",
                "shape": list(obj.shape),
                "dtype": str(obj.dtype),
            }
        if isinstance(obj, tf.Tensor):
            return {
                "__type__": "tf_tensor",
                "shape": obj.shape.as_list() if hasattr(obj.shape, "as_list") else list(obj.shape),
                "dtype": str(obj.dtype),
            }
        if isinstance(obj, tf.dtypes.DType):
            return str(obj)
        return obj

    def close(self) -> None:
        try:
            if self.realtime_file:
                self.realtime_file.flush()
                self.realtime_file.close()
        finally:
            self.llm_method.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="LLMMethod vs rule method：PyTorch->TensorFlowComparison of execution success rates of new use cases"
    )
    parser.add_argument(
        "--num-cases",
        "-n",
        type=int,
        default=DEFAULT_NUM_CASES,
        help=f"Number of test cases for each operator (default{DEFAULT_NUM_CASES}）",
    )
    parser.add_argument(
        "--max-iterations",
        "-m",
        type=int,
        default=DEFAULT_MAX_ITERATIONS,
        help="LLMThe number of iterations (this script is fixed to1）",
    )
    parser.add_argument("--start", type=int, default=1, help="Starting operator index (starting from 1）")
    parser.add_argument("--end", type=int, default=None, help="End operator index (including）")
    parser.add_argument("--operators", "-o", nargs="*", help="Specify operator list")
    parser.add_argument(
        "--workers",
        "-w",
        type=int,
        default=DEFAULT_WORKERS,
        help=f"Number of concurrent threads (default{DEFAULT_WORKERS}）",
    )
    parser.add_argument("--model", default=DEFAULT_MODEL, help=f"LLMmodel (default{DEFAULT_MODEL}）")
    parser.add_argument(
        "--key-path",
        "-k",
        default=DEFAULT_KEY_PATH,
        help=f"API keyFile path (default{DEFAULT_KEY_PATH}）",
    )
    args = parser.parse_args()

    print("=" * 80)
    print("LLMMethod vs Rule Method (name only+dtypeautomatic conversion）")
    print("=" * 80)
    print(f"📌 Number of use cases per operator: {args.num_cases}")
    print("📌 LLMNumber of iterations: 1（fixed）")
    print(f"📌 Number of concurrent threads: {args.workers}")
    print(f"📌 LLMModel: {args.model}")
    print("=" * 80)

    comparator = LLMvsRuleBasedComparator(
        key_path=args.key_path,
        model=args.model,
        num_workers=args.workers,
    )

    start_time = time.time()

    try:
        try:
            all_docs = list(comparator.llm_method.collection.find({}, {"api": 1}))
        except Exception as error:
            print(f"❌ Unable to connect to MongoDB or read operator list: {error}")
            print("Please confirm that the MongoDB service is started (default mongodb://localhost:27017/），or check network/Permission configuration。")
            return

        all_operators = [doc["api"] for doc in all_docs if "api" in doc]

        print(f"\n📋 There are total in the database {len(all_operators)} an operator")

        if args.operators:
            operator_names = args.operators
        else:
            start_idx = max(1, args.start) - 1
            end_idx = args.end if args.end is not None else len(all_operators)
            end_idx = min(end_idx, len(all_operators))
            if start_idx >= end_idx:
                raise ValueError(f"starting index {args.start} Must be less than end index {end_idx}")
            operator_names = all_operators[start_idx:end_idx]
            print(f"📌 Test range: No. {start_idx + 1} To the third {end_idx} an operator")

        print(f"📋 Actual number of test operators: {len(operator_names)}")
        preview = ", ".join(operator_names[:10])
        print(f"📋 Top 10 operators: {preview}{'...' if len(operator_names) > 10 else ''}\n")

        result = comparator.run_comparison(
            operator_names=operator_names,
            num_cases=args.num_cases,
            max_iterations=args.max_iterations,
        )

        comparator.print_and_save_results(result)

        elapsed = time.time() - start_time
        hours = int(elapsed // 3600)
        minutes = int((elapsed % 3600) // 60)
        seconds = int(elapsed % 60)
        print(f"\n⏱️ Total time spent: {hours}h {minutes}m {seconds}s")

    finally:
        comparator.close()
        print("✅ Program execution completed")


if __name__ == "__main__":
    main()
