# ./pt_tf_test/compare_llm_vs_onnx.py
"""
LLMmethod vs ONNX method：PyTorch → TensorFlow Test case conversion success rate comparison
================================================================

Compare two cross-framework test case migration solutions：
1. LLMMethod: Extract use cases from MongoDB → structurePT/TFuse case → implement → LLMrepair/Mutations → Execute use cases generated by LLM
2. ONNXMethod: Extract use cases from MongoDB → Packaged as a PyTorch mini-model → torch.onnx.export → onnxruntimereasoning  Statistical indicators: TF use case execution success rate generated by LLM vs. ONNX export+Reasoning success rate (Excluding operators that LLM chooses to skip）
"""

import pymongo
import torch
import tensorflow as tf
import numpy as np
import pandas as pd
import re
import copy
import os
import sys
import json
import argparse
import traceback
import time
import tempfile
import onnx
import onnxruntime as ort
from typing import Dict, List, Any, Tuple, Optional
from datetime import datetime
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock, RLock

# Add project root directory to path
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from component.doc.doc_crawler_factory import get_doc_content

# ==================== constant definition ====================
DEFAULT_MODEL = "qwen-plus"
DEFAULT_KEY_PATH = "aliyun.key"
DEFAULT_MAX_ITERATIONS = 1   # Simplified comparison: only iterate once
DEFAULT_NUM_CASES = 3
DEFAULT_WORKERS = 4


# ==================== Utility function ====================

def safe_print(msg: str, print_lock: Lock = None, end: str = "\n"):
    """Thread-safe printing"""
    if print_lock:
        with print_lock:
            print(msg, end=end, flush=True)
    else:
        print(msg, end=end, flush=True)


# ==================== ONNX converter ====================

class OnnxConverter:
    """
    Implemented via ONNX intermediate format PyTorch → TensorFlow Test case migration          core process：
    1. Wrap PyTorch operators into a minimal nn.Module
    2. use torch.onnx.export Export as ONNX model
    3. Use onnxruntime inference to get the output          Success Criteria: ONNX Export + OnnxRuntime Successful reasoning is regarded as"ONNXMethod conversion successful"
    """

    def __init__(self, print_lock: Lock = None):
        self.print_lock = print_lock or Lock()
        self.execution_lock = RLock()

    def _safe_print(self, msg: str, end: str = "\n"):
        safe_print(msg, self.print_lock, end)

    def _wrap_as_module(self, torch_api: str, is_class_api: bool,
                        init_kwargs: Dict[str, Any],
                        extra_kwargs: Dict[str, Any] = None) -> Optional[torch.nn.Module]:
        """
        Wrap PyTorch operators as nn.Module，so that torch.onnx.export use
        
        Args:
            torch_api: PyTorch API name
            is_class_api: Is it in class form? API
            init_kwargs: Initialization parameters of class operators
            extra_kwargs: Non-tensor keyword arguments to function operators (captured via closures）
        
        Returns:
            packaged nn.Module，Return on failure None
        """
        parts = torch_api.split(".")
        extra_kwargs = extra_kwargs or {}

        try:
            if is_class_api:
                cls = self._resolve_attr(parts)
                if cls is None:
                    return None
                instance = cls(**init_kwargs)
                if isinstance(instance, torch.nn.Module):
                    return instance
                return _FuncWrapper(lambda x, _inst=instance: _inst(x))
            else:
                func = self._resolve_attr(parts)
                if func is None:
                    return None
                # If there are additional parameters that are not tensors, capture them through a closure
                if extra_kwargs:
                    return _FuncWrapper(lambda *args, _f=func, _kw=extra_kwargs: _f(*args, **_kw))
                return _FuncWrapper(func)
        except Exception:
            return None

    @staticmethod
    def _resolve_attr(parts: List[str]):
        """according to ['torch', 'nn', 'ReLU'] Such a path to obtain attributes"""
        try:
            obj = torch
            for p in parts[1:]:  # jump over 'torch'
                obj = getattr(obj, p)
            return obj
        except AttributeError:
            return None

    def convert_and_run(self, torch_api: str, test_case: Dict[str, Any],
                        is_class_api: bool) -> Dict[str, Any]:
        """
        Perform ONNX transformation on individual test cases + reasoning                  process：
        1. Prepare PyTorch input tensors
        2. Use PyTorch to forward propagate to obtain reference results
        3. torch.onnx.export Export
        4. onnxruntime reasoning
        5. Compare the results of the two
        
        Returns:
            {
                "onnx_export_success": bool,
                "onnx_run_success": bool,
                "pt_success": bool,
                "error": str or None,
                "pt_shape": list or None,
                "onnx_shape": list or None,
            }
        """
        result = {
            "onnx_export_success": False,
            "onnx_run_success": False,
            "pt_success": False,
            "error": None,
            "pt_shape": None,
            "onnx_shape": None,
        }

        # Use execution lock guarantee torch.onnx.export Thread safety
        with self.execution_lock:
            # ---------- 1. ready to enter ----------
            try:
                input_tensors, init_kwargs, input_names, extra_kwargs = self._prepare_inputs(test_case, is_class_api)
            except Exception as e:
                result["error"] = f"Input preparation failed: {e}"
                return result

            if not input_tensors:
                result["error"] = "No valid input tensor"
                return result

            # ---------- 2. packaging model ----------
            module = self._wrap_as_module(torch_api, is_class_api, init_kwargs, extra_kwargs)
            if module is None:
                result["error"] = f"Unable to wrap operator {torch_api} for nn.Module"
                return result

            module.eval()

            # ---------- 3. PyTorch forward propagation ----------
            try:
                with torch.no_grad():
                    if len(input_tensors) == 1:
                        pt_output = module(input_tensors[0])
                    else:
                        pt_output = module(*input_tensors)
                result["pt_success"] = True
                if hasattr(pt_output, 'shape'):
                    result["pt_shape"] = list(pt_output.shape)
            except Exception as e:
                result["error"] = f"PyTorchForward propagation failed: {e}"
                return result

            # ---------- 4. ONNX Export ----------
            onnx_path = None
            try:
                onnx_fd, onnx_path = tempfile.mkstemp(suffix=".onnx")
                os.close(onnx_fd)

                if len(input_tensors) == 1:
                    dummy_input = input_tensors[0]
                else:
                    dummy_input = tuple(input_tensors)

                output_names = ["output"]
                torch.onnx.export(
                    module,
                    dummy_input,
                    onnx_path,
                    input_names=input_names,
                    output_names=output_names,
                    opset_version=14,
                    do_constant_folding=True,
                )
                result["onnx_export_success"] = True
            except Exception as e:
                result["error"] = f"ONNXExport failed: {e}"
                if onnx_path and os.path.exists(onnx_path):
                    os.remove(onnx_path)
                return result

            # ---------- 5. OnnxRuntime reasoning ----------
            try:
                sess = ort.InferenceSession(onnx_path, providers=["CPUExecutionProvider"])
                feed = {}
                for i, tensor in enumerate(input_tensors):
                    name = input_names[i] if i < len(input_names) else f"input_{i}"
                    feed[name] = tensor.detach().cpu().numpy()

                onnx_outputs = sess.run(None, feed)
                onnx_result = onnx_outputs[0]

                result["onnx_run_success"] = True
                result["onnx_shape"] = list(onnx_result.shape)

            except Exception as e:
                result["error"] = f"OnnxRuntimeReasoning failed: {e}"
            finally:
                if onnx_path and os.path.exists(onnx_path):
                    os.remove(onnx_path)

        return result

    def _prepare_inputs(self, test_case: Dict[str, Any],
                        is_class_api: bool) -> Tuple[List[torch.Tensor], Dict[str, Any], List[str], Dict[str, Any]]:
        """
        Extract input tensors and initialization parameters from test case
        
        Returns:
            (input_tensorslist, init_kwargsdictionary, input_nameslist, extra_kwargsdictionary)
            extra_kwargs: The non-tensor keyword parameters of the function operator are passed to the wrapped through closure.Module
        """
        input_tensors: List[torch.Tensor] = []
        init_kwargs: Dict[str, Any] = {}
        input_names: List[str] = []
        extra_kwargs: Dict[str, Any] = {}  # Non-tensor parameters of function operators

        # List of positional parameter names (parameters that need to be converted into tensors)）
        positional_tensor_params = ["condition", "input", "x", "y", "other"]

        # Variable parameter handling
        varargs_key = None
        for key in test_case.keys():
            if key.startswith('*'):
                varargs_key = key
                break

        if varargs_key:
            varargs_value = test_case[varargs_key]
            if isinstance(varargs_value, list):
                for idx, item in enumerate(varargs_value):
                    tensor = self._to_torch_tensor(item)
                    if tensor is not None:
                        input_tensors.append(tensor)
                        input_names.append(f"input_{idx}")
            return input_tensors, init_kwargs, input_names, extra_kwargs

        # Collect positional parameters in order as input tensor
        for param_name in positional_tensor_params:
            if param_name in test_case:
                value = test_case[param_name]
                tensor = self._to_torch_tensor(value)
                if tensor is not None:
                    input_tensors.append(tensor)
                    input_names.append(param_name)

        # Other parameters
        skip_params = {"layout", "requires_grad", "out", "api"}
        for key, value in test_case.items():
            if key in positional_tensor_params or key in skip_params or key.startswith('*'):
                continue
            if is_class_api:
                # Class operator: non-tensor parameters as initialization parameters
                if isinstance(value, np.ndarray):
                    input_tensors.append(torch.from_numpy(value.copy()))
                    input_names.append(key)
                else:
                    init_kwargs[key] = value
            else:
                # function operator
                if isinstance(value, np.ndarray):
                    input_tensors.append(torch.from_numpy(value.copy()))
                    input_names.append(key)
                elif isinstance(value, (int, float, bool, str)):
                    # Non-tensor arguments are passed via closures
                    extra_kwargs[key] = value

        return input_tensors, init_kwargs, input_names, extra_kwargs

    @staticmethod
    def _to_torch_tensor(value: Any) -> Optional[torch.Tensor]:
        """Convert values ​​in various formats to PyTorch tensors"""
        if isinstance(value, np.ndarray):
            return torch.from_numpy(value.copy())
        elif isinstance(value, dict) and "shape" in value:
            dtype_map = {
                "torch.float64": np.float64, "torch.float32": np.float32,
                "torch.int64": np.int64, "torch.int32": np.int32,
                "torch.bool": np.bool_, "torch.uint8": np.uint8,
                "float64": np.float64, "float32": np.float32,
                "int64": np.int64, "int32": np.int32,
                "bool": np.bool_, "uint8": np.uint8,
            }
            shape = value.get("shape", [])
            dtype_str = value.get("dtype", "torch.float32")
            dtype = dtype_map.get(dtype_str, np.float32)
            if shape:
                if dtype == np.bool_:
                    arr = np.random.randint(0, 2, shape).astype(np.bool_)
                elif dtype in [np.int64, np.int32]:
                    arr = np.random.randint(-10, 10, shape).astype(dtype)
                else:
                    arr = np.random.randn(*shape).astype(dtype)
            else:
                arr = np.array(1.0, dtype=dtype)
            return torch.from_numpy(arr)
        elif isinstance(value, (int, float)):
            return torch.tensor(value)
        elif isinstance(value, list):
            try:
                return torch.tensor(value)
            except Exception:
                return None
        return None


class _FuncWrapper(torch.nn.Module):
    """Wrap a normal function as nn.Module，used for torch.onnx.export"""

    def __init__(self, func):
        super().__init__()
        self._func = func

    def forward(self, *args):
        return self._func(*args)


# ==================== LLM Method (simplified version） ====================

class LLMMethod:
    """
    Test case conversion method based on LLM (simplified version, 1 iteration)          Process: Extracting use cases from MongoDB → Executed in PT and TF → LLMJudgment repair/jump over → Execute use cases generated by LLM     Reused llm_enhanced_compare.py core logic, but streamlined output。
    """

    def __init__(self, mongo_uri: str = "mongodb://localhost:27017/",
                 db_name: str = "freefuzz-torch",
                 key_path: str = DEFAULT_KEY_PATH,
                 model: str = DEFAULT_MODEL,
                 print_lock: Lock = None,
                 llm_workers: int = DEFAULT_WORKERS):
        self.model = model
        self.print_lock = print_lock or Lock()
        self.llm_workers = max(1, int(llm_workers))
        self.execution_lock = RLock()
        self.stats_lock = Lock()

        # MongoDB
        self.client = pymongo.MongoClient(mongo_uri)
        self.db = self.client[db_name]
        self.collection = self.db["argVS"]

        # LLM client
        api_key = self._load_api_key(key_path)
        self.llm_client = OpenAI(
            api_key=api_key,
            base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        )

        # API mapping
        self.api_mapping = self._load_api_mapping()

        # random seed
        np.random.seed(42)
        torch.manual_seed(42)
        tf.random.set_seed(42)

    def _safe_print(self, msg: str, end: str = "\n"):
        safe_print(msg, self.print_lock, end)

    def _load_api_key(self, key_path: str) -> str:
        if not os.path.isabs(key_path):
            key_file = os.path.join(ROOT_DIR, key_path)
        else:
            key_file = key_path
        if os.path.exists(key_file):
            try:
                with open(key_file, 'r', encoding='utf-8') as f:
                    api_key = f.read().strip()
                if api_key:
                    return api_key
            except Exception:
                pass
        api_key = os.getenv("DASHSCOPE_API_KEY")
        if api_key:
            return api_key
        return ""

    def _load_api_mapping(self) -> Dict[str, Dict[str, str]]:
        mapping_file = os.path.join(ROOT_DIR, "component", "data", "api_mappings_final.csv")
        try:
            df = pd.read_csv(mapping_file)
            mapping = {}
            for _, row in df.iterrows():
                pt_api = str(row["pytorch-api"]).strip()
                tf_api = str(row["tensorflow-api"]).strip()
                mapping[pt_api] = {"tf_api": tf_api}
            return mapping
        except Exception as e:
            self._safe_print(f"❌ Failed to load mapping table: {e}")
            return {}

    def convert_api_name(self, torch_api: str) -> Tuple[Optional[str], Optional[str], str]:
        if torch_api in self.api_mapping:
            tf_api = self.api_mapping[torch_api]["tf_api"]
            if tf_api in ("No corresponding implementation", "NONE", ""):
                return torch_api, None, "No corresponding implementation"
            return torch_api, tf_api, "mapping table"
        return torch_api, None, "Not found in mapping table"

    @staticmethod
    def is_class_based_api(api_name: str) -> bool:
        parts = api_name.split(".")
        if len(parts) >= 2:
            return any(c.isupper() for c in parts[-1])
        return False

    @staticmethod
    def get_operator_function(api_name: str, framework: str = "torch"):
        try:
            parts = api_name.split(".")
            if framework == "torch" and parts[0] == "torch":
                obj = torch
                for p in parts[1:]:
                    obj = getattr(obj, p)
                return obj
            elif framework == "tensorflow" and parts[0] == "tf":
                obj = tf
                for p in parts[1:]:
                    obj = getattr(obj, p)
                return obj
        except AttributeError:
            pass
        return None

    # -------- Data generation (reusing the logic of llm_enhanced_compare） --------

    @staticmethod
    def generate_numpy_data(data: Any) -> np.ndarray:
        if isinstance(data, dict):
            dtype_map = {
                "torch.float64": np.float64, "torch.float32": np.float32,
                "torch.int64": np.int64, "torch.int32": np.int32,
                "torch.bool": np.bool_, "torch.uint8": np.uint8,
                "float64": np.float64, "float32": np.float32,
                "int64": np.int64, "int32": np.int32,
                "bool": np.bool_, "uint8": np.uint8,
                "bool_": np.bool_, "float": np.float32, "int": np.int64,
            }
            shape = data.get("shape", [])
            dtype_str = data.get("dtype", "torch.float32")
            dtype = dtype_map.get(dtype_str, np.float32)
            if shape:
                if dtype == np.bool_:
                    return np.random.randint(0, 2, shape).astype(np.bool_)
                elif dtype in [np.int64, np.int32]:
                    return np.random.randint(-10, 10, shape).astype(dtype)
                else:
                    return np.random.randn(*shape).astype(dtype)
            else:
                return np.array(1.0 if dtype not in [np.bool_, np.int64, np.int32] else 1, dtype=dtype)
        elif isinstance(data, (int, float)):
            return np.array(data)
        elif isinstance(data, list):
            return np.array(data)
        return np.array(data)

    def prepare_shared_numpy_data(self, document: Dict[str, Any], case_index: int = 0) -> Dict[str, Any]:
        shared_data = {}
        api_name = document.get("api", "")
        if self.is_class_based_api(api_name) and "input" not in document:
            if "2d" in api_name.lower():
                default_shape = {"shape": [2, 3, 4, 4], "dtype": "torch.float32"}
            elif "1d" in api_name.lower():
                default_shape = {"shape": [2, 3, 10], "dtype": "torch.float32"}
            elif "3d" in api_name.lower():
                default_shape = {"shape": [2, 3, 4, 4, 4], "dtype": "torch.float32"}
            else:
                default_shape = {"shape": [2, 3], "dtype": "torch.float32"}
            shared_data["input"] = self.generate_numpy_data(default_shape)

        exclude_keys = ["_id", "api"]
        for key, value in document.items():
            if key not in exclude_keys:
                if key.startswith('*'):
                    if isinstance(value, list) and len(value) > 0:
                        idx = min(case_index, len(value) - 1)
                        shared_data[key] = value[idx]
                    else:
                        shared_data[key] = value
                elif isinstance(value, list):
                    if len(value) > 0:
                        idx = min(case_index, len(value) - 1)
                        param_value = value[idx]
                        if isinstance(param_value, dict):
                            shared_data[key] = self.generate_numpy_data(param_value)
                        else:
                            shared_data[key] = param_value
                else:
                    shared_data[key] = value
        return shared_data

    def get_num_test_cases(self, document: Dict[str, Any]) -> int:
        max_len = 0
        for key, value in document.items():
            if key not in ["_id", "api"] and isinstance(value, list):
                max_len = max(max_len, len(value))
        return max_len if max_len > 0 else 1

    # -------- Parameter preparation --------

    def prepare_arguments_torch(self, test_case: Dict[str, Any]) -> Tuple[List[Any], Dict[str, Any]]:
        args, kwargs = [], {}
        varargs_key = None
        for key in test_case.keys():
            if key.startswith('*'):
                varargs_key = key
                break

        if varargs_key:
            varargs_value = test_case[varargs_key]
            if isinstance(varargs_value, list):
                for item in varargs_value:
                    if isinstance(item, dict) and "shape" in item:
                        arr = self.generate_numpy_data(item)
                        args.append(torch.from_numpy(arr))
                    elif isinstance(item, np.ndarray):
                        args.append(torch.from_numpy(item.copy()))
                    else:
                        args.append(item)
            return args, kwargs

        positional_params = ["condition", "x", "y", "input", "other"]
        for param_name in positional_params:
            if param_name in test_case:
                value = test_case[param_name]
                if isinstance(value, np.ndarray):
                    args.append(torch.from_numpy(value.copy()))
                else:
                    args.append(value)

        for key, value in test_case.items():
            if key not in positional_params + ["api"]:
                if isinstance(value, np.ndarray):
                    kwargs[key] = torch.from_numpy(value.copy())
                else:
                    kwargs[key] = value
        return args, kwargs

    def prepare_arguments_tensorflow(self, test_case: Dict[str, Any], tensorflow_api: str) -> Tuple[List[Any], Dict[str, Any]]:
        args, kwargs = [], {}
        common_skip = ["layout", "requires_grad", "out"]

        varargs_key = None
        for key in test_case.keys():
            if key.startswith('*'):
                varargs_key = key
                break

        if varargs_key:
            varargs_value = test_case[varargs_key]
            if isinstance(varargs_value, list):
                for item in varargs_value:
                    if isinstance(item, dict) and "shape" in item:
                        arr = self.generate_numpy_data(item)
                        args.append(tf.convert_to_tensor(arr))
                    elif isinstance(item, np.ndarray):
                        args.append(tf.convert_to_tensor(item.copy()))
                    else:
                        args.append(item)
            return args, kwargs

        positional_params = ["condition", "x", "y", "input", "other"]
        for param_name in positional_params:
            if param_name in test_case:
                value = test_case[param_name]
                if isinstance(value, np.ndarray):
                    args.append(tf.convert_to_tensor(value.copy()))
                else:
                    args.append(value)

        for key, value in test_case.items():
            if key not in positional_params + ["api"]:
                if key in common_skip:
                    continue
                if isinstance(value, np.ndarray):
                    kwargs[key] = tf.convert_to_tensor(value.copy())
                else:
                    kwargs[key] = value
        return args, kwargs

    # -------- Execute test cases --------

    def execute_test_case(self, torch_api: str, tensorflow_api: str,
                          torch_test_case: Dict[str, Any],
                          tensorflow_test_case: Dict[str, Any]) -> Dict[str, Any]:
        """Execute test cases separately in PyTorch and TensorFlow"""
        result = {
            "torch_api": torch_api, "tensorflow_api": tensorflow_api,
            "torch_success": False, "tensorflow_success": False,
            "results_match": False,
            "torch_error": None, "tensorflow_error": None,
            "comparison_error": None, "status": "unknown"
        }

        is_class_api = self.is_class_based_api(torch_api)

        # -- PyTorch --
        torch_result = None
        try:
            torch_func = self.get_operator_function(torch_api, "torch")
            if torch_func is None:
                result["torch_error"] = f"operator {torch_api} not found"
            else:
                args, kwargs = self.prepare_arguments_torch(torch_test_case)
                if is_class_api:
                    init_kwargs = {k: v for k, v in kwargs.items() if k != 'input'}
                    instance = torch_func(**init_kwargs)
                    input_data = kwargs.get('input', args[0] if args else None)
                    if input_data is None:
                        raise ValueError("Class operator is missing input parameters")
                    with torch.no_grad():
                        torch_result = instance(input_data)
                else:
                    with torch.no_grad():
                        torch_result = torch_func(*args, **kwargs)
                result["torch_success"] = True
        except Exception as e:
            result["torch_error"] = str(e)

        # -- TensorFlow --
        tf_result = None
        try:
            tf_func = self.get_operator_function(tensorflow_api, "tensorflow")
            if tf_func is None:
                result["tensorflow_error"] = f"operator {tensorflow_api} not found"
            else:
                args, kwargs = self.prepare_arguments_tensorflow(tensorflow_test_case, tensorflow_api)
                self._precheck_tensorflow_args(tensorflow_api, args, kwargs)
                if is_class_api:
                    init_kwargs = {k: v for k, v in kwargs.items() if k not in ['x', 'input']}
                    instance = tf_func(**init_kwargs)
                    input_data = kwargs.get('x', kwargs.get('input', args[0] if args else None))
                    if input_data is None:
                        raise ValueError("Class operator missinginput/xparameter")
                    tf_result = instance(input_data)
                else:
                    tf_result = tf_func(*args, **kwargs)
                result["tensorflow_success"] = True
        except Exception as e:
            result["tensorflow_error"] = str(e)

        # -- Compare --
        if result["torch_success"] and result["tensorflow_success"]:
            try:
                torch_np = torch_result.detach().cpu().numpy() if hasattr(torch_result, 'detach') else np.array(torch_result)
                tf_np = tf_result.numpy() if hasattr(tf_result, 'numpy') else np.array(tf_result)
                if torch_np.shape != tf_np.shape:
                    result["comparison_error"] = f"Shape mismatch: {torch_np.shape} vs {tf_np.shape}"
                elif np.allclose(torch_np, tf_np, atol=1e-5, rtol=1e-5, equal_nan=True):
                    result["results_match"] = True
                else:
                    max_diff = np.max(np.abs(torch_np.astype(float) - tf_np.astype(float)))
                    result["comparison_error"] = f"biggest difference: {max_diff}"
                result["status"] = "compared"
            except Exception as e:
                result["comparison_error"] = str(e)
                result["status"] = "comparison_failed"
        elif result["torch_success"]:
            result["status"] = "tensorflow_failed"
        elif result["tensorflow_success"]:
            result["status"] = "torch_failed"
        else:
            result["status"] = "both_failed"

        return result

    @staticmethod
    def _is_vector_shape(value: Any) -> bool:
        if isinstance(value, (list, tuple)):
            return True
        if isinstance(value, np.ndarray):
            return value.ndim == 1
        if isinstance(value, tf.Tensor):
            return value.shape.rank == 1
        return False

    def _precheck_tensorflow_args(self, tensorflow_api: str, args: List[Any], kwargs: Dict[str, Any]):
        """Pre-check TensorFlow parameters to avoid underlying fatal errors"""
        if tensorflow_api == "tf.nn.conv2d_transpose":
            output_shape = kwargs.get("output_shape")
            if output_shape is None and len(args) >= 3:
                output_shape = args[2]

            if output_shape is not None and not self._is_vector_shape(output_shape):
                raise ValueError("tf.nn.conv2d_transpose The output_shape must be a 1D vector")

    def _execute_sequential(self, torch_api, tensorflow_api, torch_tc, tf_tc):
        with self.execution_lock:
            return self.execute_test_case(torch_api, tensorflow_api, torch_tc, tf_tc)

    # -------- Document crawling --------

    def fetch_api_docs(self, torch_api: str, tensorflow_api: str) -> Tuple[str, str]:
        MIN_DOC_LENGTH = 300
        torch_doc, tf_doc = "", ""
        try:
            torch_doc = get_doc_content(torch_api, "pytorch")
            if not (torch_doc and "Unable" not in torch_doc and len(torch_doc.strip()) > MIN_DOC_LENGTH):
                torch_doc = f"Unable to fetch documentation for {torch_api}"
            elif len(torch_doc) > 3000:
                torch_doc = torch_doc[:3000] + "\n... (doc truncated)"
        except Exception:
            torch_doc = ""
        try:
            tf_doc = get_doc_content(tensorflow_api, "tensorflow")
            if not (tf_doc and "Unable" not in tf_doc and len(tf_doc.strip()) > MIN_DOC_LENGTH):
                tf_doc = f"Unable to fetch documentation for {tensorflow_api}"
            elif len(tf_doc) > 3000:
                tf_doc = tf_doc[:3000] + "\n... (doc truncated)"
        except Exception:
            tf_doc = ""
        return torch_doc, tf_doc

    # -------- LLM call --------

    def call_llm(self, execution_result: Dict, torch_tc: Dict, tf_tc: Dict,
                 torch_doc: str = "", tf_doc: str = "") -> Dict[str, Any]:
        """Call LLM for repair/Mutations/Skip judgment"""
        torch_api = execution_result.get("torch_api", "")
        tensorflow_api = execution_result.get("tensorflow_api", "")
        status = execution_result.get("status", "")
        torch_success = execution_result.get("torch_success", False)
        tensorflow_success = execution_result.get("tensorflow_success", False)
        results_match = execution_result.get("results_match", False)
        torch_error = execution_result.get("torch_error", "")
        tensorflow_error = execution_result.get("tensorflow_error", "")
        comparison_error = execution_result.get("comparison_error", "")

        # Simplify PyTorch test cases to reduce token consumption
        simplified_torch_test_case = {}
        for key, value in torch_tc.items():
            if isinstance(value, np.ndarray):
                simplified_torch_test_case[key] = {"shape": list(value.shape), "dtype": str(value.dtype)}
            else:
                simplified_torch_test_case[key] = value

        # Simplify TensorFlow test cases to reduce token consumption
        simplified_tensorflow_test_case = {}
        for key, value in tf_tc.items():
            if isinstance(value, np.ndarray):
                simplified_tensorflow_test_case[key] = {"shape": list(value.shape), "dtype": str(value.dtype)}
            else:
                simplified_tensorflow_test_case[key] = value

        # Build PyTorch parameter example
        torch_param_examples = []
        for key, value in simplified_torch_test_case.items():
            if key == "api":
                continue
            if isinstance(value, dict) and "shape" in value:
                torch_param_examples.append(f'    "{key}": {json.dumps(value)}')
            elif isinstance(value, (int, float)):
                torch_param_examples.append(f'    "{key}": {value}')
            else:
                torch_param_examples.append(f'    "{key}": {json.dumps(value)}')

        torch_param_example_str = ",\n".join(torch_param_examples) if torch_param_examples else '    "input": {"shape": [2, 3], "dtype": "torch.float32"}'

        # Build TensorFlow parameter example
        tf_param_examples = []
        for key, value in simplified_tensorflow_test_case.items():
            if key == "api":
                continue
            if isinstance(value, dict) and "shape" in value:
                tf_param_examples.append(f'    "{key}": {json.dumps(value)}')
            elif isinstance(value, (int, float)):
                tf_param_examples.append(f'    "{key}": {value}')
            else:
                tf_param_examples.append(f'    "{key}": {json.dumps(value)}')

        tf_param_example_str = ",\n".join(tf_param_examples) if tf_param_examples else '    "x": {"shape": [2, 3], "dtype": "float32"}'

        # Build API documentation section
        doc_section = ""
        if torch_doc or tf_doc:
            doc_section = "\n## Official API document reference\n\n"
            if torch_doc:
                doc_section += f"### PyTorch {torch_api} document\n```\n{torch_doc}\n```\n\n"
            if tf_doc:
                doc_section += f"### TensorFlow {tensorflow_api} document\n```\n{tf_doc}\n```\n\n"

        prompt = f"""Please analyze the execution results of the following operator test cases in PyTorch and TensorFlow frameworks, and make repairs or mutations of the test cases based on the results.（fuzzing）。

## Test information
- **PyTorch API**: {torch_api}
- **TensorFlow API**: {tensorflow_api}
{doc_section}
## Execution result
- **Execution status**: {status}
- **PyTorchExecuted successfully**: {torch_success}
- **TensorFlowExecuted successfully**: {tensorflow_success}
- **Are the results consistent?**: {results_match}

## error message
- **PyTorchmistake**: {torch_error if torch_error else "none"}
- **TensorFlowmistake**: {tensorflow_error if tensorflow_error else "none"}
- **comparison error**: {comparison_error if comparison_error else "none"}

## Original test case

### PyTorchtest case
```json
{json.dumps(simplified_torch_test_case, indent=2, ensure_ascii=False)}
```

### TensorFlowtest case
```json
{json.dumps(simplified_tensorflow_test_case, indent=2, ensure_ascii=False)}
```

## Mission requirements Please judge the comparison result between the two frameworks based on the above information (including official API documents).**consistent**、**inconsistent**still**Execution error**，and do the following：

1. **if consistent**：Perform on use cases**Mutations（fuzzing）**，For example, modify the shape of the input tensor, modify parameter values, etc. (you can consider some extreme values ​​or boundary values）
2. **If an error occurs during execution**：Conduct use cases based on error reasons and official documents**repair**（Change parameter names, quantities, types, value ranges, etc. (different frameworks may not be exactly the same) or**jump over**（When you think that the functions of these two cross-framework operators are not completely equivalent）
3. **if inconsistent**：Determine whether it is a tolerable precision error (1e-3 and below): (1) If it is a tolerable precision error, then**Mutations**；（2）After combined with the operator document analysis, select when it is believed that the functions of the two cross-framework operators are not completely equivalent.**jump over**；（3）If the precision error is neither tolerable nor the functions of the two operators are equivalent, it is a test case construction problem. Please conduct the test case according to the operator documentation.**repair**。

## Output format requirements Please strictly follow the following JSON format and do not include any other text, comments or markdown tags：

{{
  "operation": "mutation",
  "reason": "Detailed reasons for doing this",
  "pytorch_test_case": {{
    "api": "{torch_api}",
{torch_param_example_str}
  }},
  "tensorflow_test_case": {{
    "api": "{tensorflow_api}",
{tf_param_example_str}
  }}
}}

**Important note**：
1. operationThe value must be "mutation"、"repair" or "skip" one
2. Tensor parameters must be used {{"shape": [...], "dtype": "..."}} Format
3. Scalar parameters use numeric values ​​directly, e.g. "y": 0
4. When constructing use cases for the two frameworks, you must ensure that the inputs are the same (convert the tensor shape if necessary, such as NHWC and NCHW conversion), and the parameters are strictly semantically corresponding. For example, the "pad" parameter, in PyTorchpadding=1Does not strictly correspond to TensorFlowpadding='SAME'，An equivalent pad operation must be performed。
5. PyTorchTest cases with TensorFlow can have differences in parameter names (such as input vs x), parameter values, or number of parameters, as long as the theoretical output is the same.。
6. If the official document cannot be found for this operator, please determine whether it is because the operator does not exist or has been removed from the current version of PyTorch or TensorFlow. If so, please set operation to "skip"，No need to try to fix。
7. When test cases are mutated, some extreme cases can be appropriately explored, such as: empty tensor (shape contains 0), single-element tensor（shape=[1]or []), high-dimensional tensors, very large tensors, different data types (int, float, bool), boundary values, etc., to improve test coverage and discover potentialbug
8. Please read the official API documentation carefully to ensure that parameter names, parameter types, parameter value ranges, etc. are consistent with the documentation.
"""

        try:
            completion = self.llm_client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert in deep learning framework testing and are proficient in the API differences between PyTorch and TensorFlow. Return results in strict JSON format。"},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.1,
            )
            raw = completion.choices[0].message.content.strip()
            time.sleep(1)
            try:
                return json.loads(raw)
            except json.JSONDecodeError:
                match = re.search(r'\{.*\}', raw, re.DOTALL)
                if match:
                    return json.loads(match.group())
                return {"operation": "skip", "reason": "LLMReturn format error"}
        except Exception as e:
            return {"operation": "skip", "reason": f"LLMcall failed: {e}"}

    # -------- Convert LLM test cases --------

    def convert_llm_test_cases(self, pt_tc: Dict, tf_tc: Dict) -> Tuple[Dict, Dict]:
        """Convert test cases returned by LLM into executable format (shared tensor data）"""
        shared_tensors = {}
        all_keys = set(pt_tc.keys()) | set(tf_tc.keys())
        for key in all_keys:
            if key == "api":
                continue
            pt_val = pt_tc.get(key)
            tf_val = tf_tc.get(key)
            tensor_desc = None
            if isinstance(pt_val, dict) and "shape" in pt_val:
                tensor_desc = pt_val
            elif isinstance(tf_val, dict) and "shape" in tf_val:
                tensor_desc = tf_val
            if tensor_desc:
                shared_tensors[key] = self.generate_numpy_data(tensor_desc)

        converted_pt = {}
        for k, v in pt_tc.items():
            converted_pt[k] = shared_tensors.get(k, v)
        converted_tf = {}
        for k, v in tf_tc.items():
            converted_tf[k] = shared_tensors.get(k, v)
        return converted_pt, converted_tf

    def close(self):
        self.client.close()


# ==================== main comparison logic ====================

class LLMvsONNXComparator:
    """
    Main comparison category: Comparative test of unified management LLM method and ONNX method          Run two methods at the same time for each use case of each operator, and finally summarize the statistics。
    """

    def __init__(self, key_path: str = DEFAULT_KEY_PATH,
                 model: str = DEFAULT_MODEL,
                 num_workers: int = DEFAULT_WORKERS):
        self.print_lock = Lock()
        self.num_workers = max(1, num_workers)
        self.execution_lock = RLock()
        self.realtime_lock = Lock()

        self.llm_method = LLMMethod(
            key_path=key_path, model=model,
            print_lock=self.print_lock,
            llm_workers=self.num_workers
        )
        self.onnx_converter = OnnxConverter(print_lock=self.print_lock)

        # Results directory
        self.result_dir = os.path.join(ROOT_DIR, "pt_tf_test")
        os.makedirs(self.result_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.realtime_file_path = os.path.join(self.result_dir, f"llm_vs_onnx_realtime_{timestamp}.jsonl")
        self.realtime_file = open(self.realtime_file_path, "a", encoding="utf-8")

    def _safe_print(self, msg: str, end: str = "\n"):
        safe_print(msg, self.print_lock, end)

    def _append_realtime_record(self, record: Dict[str, Any]):
        """Write a single statistical record in real time（JSONL）"""
        with self.realtime_lock:
            self.realtime_file.write(json.dumps(record, ensure_ascii=False) + "\n")
            self.realtime_file.flush()

    def run_comparison(self, operator_names: List[str],
                       num_cases: int = DEFAULT_NUM_CASES,
                       max_iterations: int = DEFAULT_MAX_ITERATIONS) -> Dict[str, Any]:
        """
        Run LLM vs ONNX comparison test on a batch of operators                  Returns a dictionary of summary results
        """
        # global statistics
        global_stats = {
            "total_operators": len(operator_names),
            "tested_operators": 0,
            "skipped_operators_llm": 0,      # LLMSelect the number of operators to skip
            "skipped_operators_no_tf": 0,     # Number of operators without TF mapping
            "skipped_operators_deprecated": 0,  # The number of operators skipped by the version

            # LLM Method statistics (after excluding skipped operators)）
            "llm_total_cases": 0,            # LLMTotal number of TF test cases generated
            "llm_tf_success": 0,             # TFThe number of successful executions

            # ONNX Method statistics (after excluding skipped operators)）
            "onnx_total_cases": 0,           # ONNXTotal number of conversion attempts
            "onnx_export_success": 0,        # ONNXNumber of successful exports
            "onnx_run_success": 0,           # ONNXThe number of successful inferences (i.e."Conversion successful"）
        }

        operator_details = []  # Detailed results for each operator

        for idx, op_name in enumerate(operator_names, 1):
            self._safe_print(f"\n{'='*70}")
            self._safe_print(f"[{idx}/{len(operator_names)}] operator: {op_name}")
            self._safe_print(f"{'='*70}")

            # 1. Check API mapping
            torch_api, tf_api, mapping_method = self.llm_method.convert_api_name(op_name)
            if tf_api is None:
                self._safe_print(f"  ⏭️ No TF corresponding implementation（{mapping_method}），jump over")
                global_stats["skipped_operators_no_tf"] += 1
                operator_details.append({
                    "operator": op_name, "status": "skipped_no_tf",
                    "mapping_method": mapping_method
                })
                continue

            self._safe_print(f"  PT: {torch_api} → TF: {tf_api}")

            # 2. Get documents from MongoDB
            document = self.llm_method.collection.find_one({"api": op_name})
            if document is None:
                self._safe_print(f"  ❌ Not found in database")
                operator_details.append({"operator": op_name, "status": "not_found"})
                continue

            total_cases = self.llm_method.get_num_test_cases(document)
            actual_cases = min(num_cases, total_cases)

            # 3. Test both LLM and ONNX
            op_result = self._test_operator(
                op_name, torch_api, tf_api, document,
                actual_cases, max_iterations
            )

            operator_details.append(op_result)

            # 4. Summary statistics (operator that skips LLM skip）
            if op_result["status"] == "skipped_by_llm":
                global_stats["skipped_operators_llm"] += 1
            elif op_result["status"] == "skipped_deprecated":
                global_stats["skipped_operators_deprecated"] += 1
            else:
                global_stats["tested_operators"] += 1
                global_stats["llm_total_cases"] += op_result["llm_total"]
                global_stats["llm_tf_success"] += op_result["llm_tf_success"]
                global_stats["onnx_total_cases"] += op_result["onnx_total"]
                global_stats["onnx_export_success"] += op_result["onnx_export_success"]
                global_stats["onnx_run_success"] += op_result["onnx_run_success"]

        return {"global_stats": global_stats, "operator_details": operator_details}

    def _test_operator(self, op_name: str, torch_api: str, tf_api: str,
                       document: Dict, num_cases: int,
                       max_iterations: int) -> Dict[str, Any]:
        """
        Simultaneous testing of LLM and ONNX methods for multiple use cases of a single operator                  Using a thread pool for concurrent LLM calls, ONNX transformations and operator execution are executed sequentially through locks
        """
        op_result = {
            "operator": op_name,
            "torch_api": torch_api,
            "tf_api": tf_api,
            "status": "completed",
            "num_cases": num_cases,
            "llm_total": 0,
            "llm_tf_success": 0,
            "onnx_total": 0,
            "onnx_export_success": 0,
            "onnx_run_success": 0,
            "case_details": []
        }

        is_class_api = self.llm_method.is_class_based_api(torch_api)

        # Prepare all test cases
        cases = []
        for case_idx in range(num_cases):
            tc = self.llm_method.prepare_shared_numpy_data(document, case_index=case_idx)
            tc["api"] = torch_api
            cases.append((case_idx + 1, tc))

        # Pre-crawl documents (crawl only once）
        self._safe_print(f"  📖 Crawl API documentation...")
        torch_doc, tf_doc = self.llm_method.fetch_api_docs(torch_api, tf_api)

        # Use a thread pool to process each use case concurrently
        if self.num_workers <= 1:
            case_results = []
            for case_number, tc in cases:
                cr = self._process_single_case(
                    torch_api, tf_api, tc, case_number,
                    is_class_api, torch_doc, tf_doc, max_iterations
                )
                case_results.append(cr)
        else:
            case_results = []
            with ThreadPoolExecutor(max_workers=self.num_workers) as executor:
                future_map = {}
                for case_number, tc in cases:
                    future = executor.submit(
                        self._process_single_case,
                        torch_api, tf_api, tc, case_number,
                        is_class_api, torch_doc, tf_doc, max_iterations
                    )
                    future_map[future] = case_number
                for future in as_completed(future_map):
                    case_results.append(future.result())

        case_results.sort(key=lambda x: x["case_number"])

        # Check if skipped due to version obsolescence (priority higher thanLLM skip）
        any_deprecated = any(cr.get("deprecated_skip", False) for cr in case_results)
        if any_deprecated:
            op_result["status"] = "skipped_deprecated"
            op_result["case_details"] = case_results
            self._safe_print("  ⏭️ This operator has been eliminated from the version and will be skipped.")
            return op_result

        # Check if all use cases are covered LLM skip
        all_skipped = all(cr.get("llm_skipped", False) for cr in case_results)
        if all_skipped and len(case_results) > 0:
            op_result["status"] = "skipped_by_llm"
            op_result["case_details"] = case_results
            self._safe_print(f"  ⏭️ LLMChoose to skip this operator")
            return op_result

        # Aggregate results for each use case
        for cr in case_results:
            if not cr.get("llm_skipped", False):
                op_result["llm_total"] += cr.get("llm_total", 0)
                op_result["llm_tf_success"] += cr.get("llm_tf_success", 0)
                # ONNX statistics only count non-skipped cases to keep a consistent denominator
                op_result["onnx_total"] += cr.get("onnx_total", 0)
                op_result["onnx_export_success"] += cr.get("onnx_export_success", 0)
                op_result["onnx_run_success"] += cr.get("onnx_run_success", 0)
        op_result["case_details"] = case_results

        return op_result

    def _process_single_case(self, torch_api: str, tf_api: str,
                             test_case: Dict[str, Any], case_number: int,
                             is_class_api: bool,
                             torch_doc: str, tf_doc: str,
                             max_iterations: int) -> Dict[str, Any]:
        """
        Addressing a single use case: LLM approach and ONNX approach simultaneously                  LLM method flow (1 iteration）：
          1. Executed in PT and TF with DB use cases
          2. Call LLM to get fix/Mutations/jump over
          3. If LLM returnsmutation/repair，Execute use cases generated by LLM                  ONNX method flow：
          1. Use the same DB use case and wrap it intoPyTorch Module
          2. torch.onnx.export + onnxruntimereasoning
        """
        case_result = {
            "case_number": case_number,
            "llm_skipped": False,
            "deprecated_skip": False,
            "llm_total": 0,
            "llm_tf_success": 0,
            "onnx_total": 0,
            "onnx_export_success": 0,
            "onnx_run_success": 0,
            "llm_detail": None,
            "onnx_detail": None,
        }

        # ========== ONNX method ==========
        self._safe_print(f"  [use case{case_number}] ONNXmethod...", end="")
        with self.execution_lock:
            onnx_result = self.onnx_converter.convert_and_run(
                torch_api, test_case, is_class_api
            )
        case_result["onnx_total"] = 1
        if onnx_result["onnx_export_success"]:
            case_result["onnx_export_success"] = 1
        if onnx_result["onnx_run_success"]:
            case_result["onnx_run_success"] = 1

        onnx_status = "✓" if onnx_result["onnx_run_success"] else "✗"
        onnx_err = f" ({onnx_result['error'][:60]})" if onnx_result.get("error") else ""
        self._safe_print(f" ONNX:{onnx_status}{onnx_err}")
        case_result["onnx_detail"] = onnx_result

        # ========== LLM method ==========
        # Step 1: Execute in both frameworks with DB original use case
        torch_test_case = test_case
        tf_test_case = copy.deepcopy(test_case)
        tf_test_case["api"] = tf_api

        self._safe_print(f"  [use case{case_number}] LLMmethod: initial execution...", end="")
        try:
            with self.execution_lock:
                exec_result = self.llm_method._execute_sequential(
                    torch_api, tf_api, torch_test_case, tf_test_case
                )
            pt_s = "✓" if exec_result['torch_success'] else "✗"
            tf_s = "✓" if exec_result['tensorflow_success'] else "✗"
            self._safe_print(f" PT:{pt_s} TF:{tf_s}")
        except Exception as e:
            self._safe_print(f" ❌ Execution failed: {str(e)[:60]}")
            exec_result = {
                "torch_api": torch_api, "tensorflow_api": tf_api,
                "torch_success": False, "tensorflow_success": False,
                "results_match": False, "status": "fatal_error",
                "torch_error": str(e), "tensorflow_error": None,
                "comparison_error": None
            }

        # If PyTorch executes the error message containsdeprecated/removed，Skip this operator directly
        torch_error = str(exec_result.get("torch_error", ""))
        if not exec_result.get("torch_success", False) and torch_error:
            if re.search(r"deprecated|removed", torch_error, re.IGNORECASE):
                case_result["deprecated_skip"] = True
                case_result["llm_skipped"] = False
                case_result["llm_detail"] = {
                    "initial_exec": exec_result,
                    "llm_operation": "skip",
                    "llm_reason": "PyTorchThe operator has been eliminated by the version"
                }
                self._safe_print(" Version obsolescence detected, skipped")
                self._append_realtime_record({
                    "timestamp": datetime.now().isoformat(),
                    "operator": torch_api,
                    "case_number": case_number,
                    "status": "skipped_deprecated",
                    "onnx_run_success": bool(case_result.get("onnx_run_success", 0)),
                    "llm_tf_success": False,
                    "llm_skipped": False,
                    "deprecated_skip": True
                })
                return case_result

        # Step 2: CallLLM
        self._safe_print(f"  [use case{case_number}] callLLM...", end="")
        llm_result = self.llm_method.call_llm(
            exec_result, torch_test_case, tf_test_case, torch_doc, tf_doc
        )
        operation = llm_result.get("operation", "skip")
        reason = llm_result.get("reason", "")[:60]
        self._safe_print(f" {operation} - {reason}")

        if operation == "skip":
            case_result["llm_skipped"] = True
            case_result["llm_detail"] = {
                "initial_exec": exec_result,
                "llm_operation": operation,
                "llm_reason": llm_result.get("reason", "")
            }
            self._append_realtime_record({
                "timestamp": datetime.now().isoformat(),
                "operator": torch_api,
                "case_number": case_number,
                "status": "llm_skip",
                "onnx_run_success": bool(case_result.get("onnx_run_success", 0)),
                "llm_tf_success": False,
                "llm_skipped": True,
                "deprecated_skip": False
            })
            return case_result

        # Step 3: If LLM returnsmutation/repair，Execute use cases generated by LLM
        llm_pt_tc = llm_result.get("pytorch_test_case", torch_test_case)
        llm_tf_tc = llm_result.get("tensorflow_test_case", tf_test_case)

        # Convert to executable format
        try:
            llm_pt_tc, llm_tf_tc = self.llm_method.convert_llm_test_cases(llm_pt_tc, llm_tf_tc)
        except Exception as e:
            case_result["llm_skipped"] = True
            case_result["llm_detail"] = {
                "initial_exec": exec_result,
                "llm_operation": "skip",
                "llm_reason": f"LLMThe returned shape is illegal or the tensor cannot be generated.: {e}"
            }
            self._safe_print(f"  [use case{case_number}] LLMUse case conversion failed, skipped: {str(e)[:60]}")
            self._append_realtime_record({
                "timestamp": datetime.now().isoformat(),
                "operator": torch_api,
                "case_number": case_number,
                "status": "llm_case_convert_failed",
                "onnx_run_success": bool(case_result.get("onnx_run_success", 0)),
                "llm_tf_success": False,
                "llm_skipped": True,
                "deprecated_skip": False
            })
            return case_result

        case_result["llm_total"] = 1

        self._safe_print(f"  [use case{case_number}] Execute LLM use cases...", end="")
        try:
            with self.execution_lock:
                llm_exec = self.llm_method._execute_sequential(
                    torch_api, tf_api, llm_pt_tc, llm_tf_tc
                )
            pt_s = "✓" if llm_exec['torch_success'] else "✗"
            tf_s = "✓" if llm_exec['tensorflow_success'] else "✗"
            match_s = "✓" if llm_exec['results_match'] else "✗"
            self._safe_print(f" PT:{pt_s} TF:{tf_s} Match:{match_s}")

            if llm_exec["tensorflow_success"]:
                case_result["llm_tf_success"] = 1

        except Exception as e:
            self._safe_print(f" ❌ {str(e)[:60]}")
            llm_exec = {
                "torch_success": False, "tensorflow_success": False,
                "results_match": False, "status": "fatal_error",
                "error": str(e)
            }

        case_result["llm_detail"] = {
            "initial_exec": exec_result,
            "llm_operation": operation,
            "llm_reason": llm_result.get("reason", ""),
            "llm_exec": llm_exec
        }

        self._append_realtime_record({
            "timestamp": datetime.now().isoformat(),
            "operator": torch_api,
            "case_number": case_number,
            "status": "completed",
            "onnx_run_success": bool(case_result.get("onnx_run_success", 0)),
            "llm_tf_success": bool(case_result.get("llm_tf_success", 0)),
            "llm_skipped": False,
            "deprecated_skip": False
        })

        return case_result

    def print_and_save_results(self, comparison_result: Dict[str, Any]):
        """Print results and save to file"""
        gs = comparison_result["global_stats"]

        print("\n" + "=" * 80)
        print("📊 LLMMethod vs ONNX method - test case conversion success rate comparison")
        print("=" * 80)

        print(f"\n📌 Total number of operators: {gs['total_operators']}")
        print(f"   - Skip without TF mapping: {gs['skipped_operators_no_tf']}")
        print(f"   - LLMSelect skip: {gs['skipped_operators_llm']}")
        print(f"   - Has been eliminated and skipped by version: {gs['skipped_operators_deprecated']}")
        print(f"   - Actual participation comparison: {gs['tested_operators']}")

        print(f"\n{'─'*40}")
        print(f"🤖 LLM Method (eliminate skipped operators）:")
        print(f"   LLMTotal number of TF test cases generated: {gs['llm_total_cases']}")
        print(f"   TFNumber of successful executions: {gs['llm_tf_success']}")
        if gs['llm_total_cases'] > 0:
            llm_rate = gs['llm_tf_success'] / gs['llm_total_cases'] * 100
            print(f"   ✅ TFExecution success rate: {llm_rate:.2f}%")
        else:
            llm_rate = 0
            print(f"   ✅ TFExecution success rate: N/A（Use cases generated without LLM）")

        print(f"\n{'─'*40}")
        print(f"🔄 ONNX Method (eliminate operators skipped by LLM）:")
        print(f"   ONNXTotal conversion attempts: {gs['onnx_total_cases']}")
        print(f"   ONNXNumber of successful exports: {gs['onnx_export_success']}")
        print(f"   ONNXNumber of successful inferences（=Conversion successful）: {gs['onnx_run_success']}")
        if gs['onnx_total_cases'] > 0:
            onnx_rate = gs['onnx_run_success'] / gs['onnx_total_cases'] * 100
            print(f"   ✅ ONNXConversion success rate: {onnx_rate:.2f}%")
        else:
            onnx_rate = 0
            print(f"   ✅ ONNXConversion success rate: N/A")

        print(f"\n{'─'*40}")
        print(f"📈 Comparative conclusion:")
        if gs['llm_total_cases'] > 0 and gs['onnx_total_cases'] > 0:
            diff = llm_rate - onnx_rate
            if diff > 0:
                print(f"   LLMMethod is better than ONNX method {diff:.2f} percentage points")
            elif diff < 0:
                print(f"   ONNXMethod is better than LLM method {-diff:.2f} percentage points")
            else:
                print(f"   The success rates of the two methods are the same")
        else:
            print(f"   Insufficient data to compare")
        print("=" * 80)

        # -------- save to file --------
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        result_file = os.path.join(self.result_dir, f"llm_vs_onnx_result_{timestamp}.json")

        # Clean up non-serializable content
        save_data = self._make_serializable(comparison_result)
        save_data["summary"] = {
            "llm_tf_success_rate": f"{llm_rate:.2f}%" if gs['llm_total_cases'] > 0 else "N/A",
            "onnx_success_rate": f"{onnx_rate:.2f}%" if gs['onnx_total_cases'] > 0 else "N/A",
            "skipped_operators_deprecated": gs.get("skipped_operators_deprecated", 0),
            "timestamp": datetime.now().isoformat()
        }

        with open(result_file, 'w', encoding='utf-8') as f:
            json.dump(save_data, f, indent=2, ensure_ascii=False)

        print(f"\n💾 Detailed results have been saved to: {result_file}")

    @staticmethod
    def _make_serializable(obj: Any) -> Any:
        """Recursively convert objects into a JSON serializable format"""
        if isinstance(obj, dict):
            return {k: LLMvsONNXComparator._make_serializable(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [LLMvsONNXComparator._make_serializable(item) for item in obj]
        elif isinstance(obj, np.ndarray):
            return {"__type__": "ndarray", "shape": list(obj.shape), "dtype": str(obj.dtype)}
        elif isinstance(obj, (np.integer,)):
            return int(obj)
        elif isinstance(obj, (np.floating,)):
            return float(obj)
        elif isinstance(obj, np.bool_):
            return bool(obj)
        elif isinstance(obj, (torch.Tensor,)):
            return {"__type__": "tensor", "shape": list(obj.shape), "dtype": str(obj.dtype)}
        elif isinstance(obj, bytes):
            return "<bytes>"
        else:
            return obj

    def close(self):
        try:
            if self.realtime_file:
                self.realtime_file.flush()
                self.realtime_file.close()
        finally:
            self.llm_method.close()


# ==================== main function ====================

def main():
    parser = argparse.ArgumentParser(
        description="LLMmethod vs ONNX method：PyTorch→TensorFlowTest case conversion success rate comparison"
    )
    parser.add_argument("--num-cases", "-n", type=int, default=DEFAULT_NUM_CASES,
                        help=f"The number of test cases for each operator test (default{DEFAULT_NUM_CASES}）")
    parser.add_argument("--max-iterations", "-m", type=int, default=DEFAULT_MAX_ITERATIONS,
                        help=f"LLMThe number of iterations per use case of the method (default{DEFAULT_MAX_ITERATIONS}）")
    parser.add_argument("--start", type=int, default=1,
                        help="Starting operator index (starting from 1）")
    parser.add_argument("--end", type=int, default=None,
                        help="End operator index (including）")
    parser.add_argument("--operators", "-o", nargs="*",
                        help="Specify operator name list")
    parser.add_argument("--workers", "-w", type=int, default=DEFAULT_WORKERS,
                        help=f"LLMNumber of concurrent threads (default{DEFAULT_WORKERS}）")
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help=f"LLMmodel (default{DEFAULT_MODEL}）")
    parser.add_argument("--key-path", "-k", default=DEFAULT_KEY_PATH,
                        help=f"API keypath (default{DEFAULT_KEY_PATH}）")
    args = parser.parse_args()

    print("=" * 80)
    print("LLMmethod vs ONNX method — PyTorch→TensorFlow Test case conversion success rate comparison")
    print("=" * 80)
    print(f"📌 Number of use cases for each operator: {args.num_cases}")
    print(f"📌 LLMNumber of iterations: {args.max_iterations}")
    print(f"📌 Number of concurrent threads: {args.workers}")
    print(f"📌 LLMModel: {args.model}")
    print("=" * 80)

    comparator = LLMvsONNXComparator(
        key_path=args.key_path, model=args.model,
        num_workers=args.workers
    )

    start_time = time.time()

    try:
        # Get operator list
        all_docs = list(comparator.llm_method.collection.find({}, {"api": 1}))
        all_ops = [doc["api"] for doc in all_docs if "api" in doc]
        print(f"\n📋 Database CCP {len(all_ops)} an operator")

        if args.operators:
            operator_names = args.operators
        else:
            start_idx = max(1, args.start) - 1
            end_idx = args.end if args.end is not None else len(all_ops)
            end_idx = min(end_idx, len(all_ops))
            operator_names = all_ops[start_idx:end_idx]
            print(f"📌 Test range: No. {start_idx + 1} ~ {end_idx} an operator")

        print(f"📋 will test {len(operator_names)} an operator")
        print(f"📋 Top 10: {', '.join(operator_names[:10])}{'...' if len(operator_names) > 10 else ''}\n")

        # Run comparison
        result = comparator.run_comparison(
            operator_names,
            num_cases=args.num_cases,
            max_iterations=args.max_iterations
        )

        # output and save
        comparator.print_and_save_results(result)

        elapsed = time.time() - start_time
        h, m, s = int(elapsed // 3600), int((elapsed % 3600) // 60), int(elapsed % 60)
        print(f"\n⏱️ Total time spent: {h}h {m}m {s}s")

    finally:
        comparator.close()
        print("✅ Program execution completed")


if __name__ == "__main__":
    main()
